---
title: ФРС
author: 'Коваленко Виктория'
date: '2017-06-20'
slug: ''
categories: []
tags:
  - FRS
subtitle: ''
---
<p style="text-align:justify;font-family:'Kievit' ;max-width: 80%; margin: auto;text-indent: 25px;color:black; line-height: 2;font-size: 12pt;">
Вчерашнее решение Федеральной Резервной системы относительно ключевой ставки, как и прогнозировалось, малозаметно отразилось на рынке. Повышение ключевой fed funds rate на 0,25% до уровней 1-1,25% к моменту оглашения решения было уже полностью заложено в ценах. Из опрошенных агентством Bloomberg ста экономистов, 95 ожидали повышение на 25 п.п.
Гораздо больше рынок ждал от пресс-конференции председателя ФРС Джанет Йеллен, в лице которой воплощено видение регулятора по дальнейшим шагам нормализации монетарной политики. 
Первый вопрос, к которому было приковано внимание участников рынка, это обоснование планируемых ФРС еще четырех раундов повышения ставки до конца 2018 года, тогда как, судя по данным фьючерсов на процентную ставку, рынок склонен ожидать только один или два повышения. 
Второй острый вопрос на повестке – как ФРС планирует избавляться от накопленных в результате QE активов на балансе в рекордном объеме $4,5 трлн. 
Для этих целей Комитетом вместе с решением по ставке было выпущено официальное Дополнение к плану нормализации, выпущенному в 2014 году. Комитет по операциям на открытом рынке будет постепенно урезать активы путем сокращения нормы реинвестирования основных платежей, которые регулятор получает от владения казначейскими и ипотечными облигациями. Более детально, это будет происходить следующим образом:
<br>
• Основные платежи, которые Федрезерв получает при наступлении срока погашения казначейских ценных бумаг, будут реинвестироваться только если их сумма превысит некоторое пороговое значение. Это значение будет постепенно увеличиваться каждые 3 месяца на $6 млрд. в течение года, составляя для начала $6 млрд. в месяц, пока не достигнет $30 млрд. в месяц. 
• Что касается ипотечных ценных бумаг, Комитет планирует, что их граничное значение для реинвестирования будет составлять $4 млрд. в месяц и будет увеличиваться с шагом в $4 млрд. пока не достигнет $20 млрд. в месяц.
При этом председатель уточнила, что Комитет не может назвать конкретного значения, до которого планируется снизить активы ФРС. Эта цифра будет зависеть как от спроса банковской системы на резервы, так и от общего состояния экономики. Однако, по словам Джанет Йеллен, эта цифра находится между предкризисным и текущим уровнями, то есть как минимум $1 трлн.
На наш взгляд, есть основания предполагать, что рынок более объективно оценивает возможности для повышения ключевой ставки в соответствии с текущей ситуацией. Об этом говорят более слабые чем ожидалось последние данные по инфляции, которые, однако, Комитет счел несущественными для корректировки своих прогнозов. Мы придерживаемся более осторожного прогноза, подразумевающего еще одно повышение ставки на 25 п.п. до конца года.<p>
